Iro_map/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls import url           
from Iro_map import *                                                                                                                   

urlpatterns = [
    path('', include('maps.urls')),
    path('admin/', admin.site.urls),
    url('^/ajax/', include("maps.urls")),
]

maps/urls.py
from django.conf.urls import url    
from . import views
urlpatterns = [ 
    url('', views.home, name="home"),
]

maps/models.py
from django.db import models


date_choices = [
                ('2021', '2021'),
                ('2020', '2020'),
                ('2019', '2019'),
                ('2018', '2018'),
                ('2017', '2017')
]




# Create your models here.
class Friend(models.Model):
    # NICK NAME should be unique
    nick_name = models.CharField(max_length=100, unique =  True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    likes = models.CharField(max_length = 250)
    dob = models.DateField(auto_now=False, auto_now_add=False)
    lives_in = models.CharField(max_length=150, null = True, blank = True)

    def __str__(self):
        return self.nick_name

class Coords(models.Model):
    lat = models.CharField(max_length=100)
    lon = models.CharField(max_length=100)

    def __str__(self):
        return (f'{self.lat}, {self.lon}')

class Profile(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)


class DateTimesModel(models.Model):
    dates = models.CharField(max_length=5, choices=date_choices)

maps/forms.py
from .models import Friend
from django import forms
import datetime
from .models import DateTimesModel


date_choices = [
                ('2021', '2021'),
                ('2020', '2020'),
                ('2019', '2019'),
                ('2018', '2018'),
                ('2017', '2017')
]



class FriendForm(forms.ModelForm):
    ## change the widget of the date field.
    dob = forms.DateField(
        label='What is your birth date?', 
        # change the range of the years from 1980 to currentYear - 5
        widget=forms.SelectDateWidget(years=range(1980, datetime.date.today().year-5))
    )
    
    def __init__(self, *args, **kwargs):
        super(FriendForm, self).__init__(*args, **kwargs)
        ## add a "form-control" class to each form input
        ## for enabling bootstrap
        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
            })

    class Meta:
        model = Friend
        fields = ("__all__")


class DatetmeModelForm(forms.Form):
    choose_date = forms.ChoiceField(choices=date_choices)

maps/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
import urllib.request
import json
import io, base64
from . import forms
import datetime
import re
from django.core import serializers
import pprint
from django.http import JsonResponse
from .forms import FriendForm, DatetmeModelForm
from .models import Friend, Coords
import pandas as pd
from statistics import mean
from math import ceil
import matplotlib.pyplot as plt
from io import BytesIO, StringIO
from .utils import get_graph, get_plot, get_plotly_graph
import plotly

#weather url days syntax - "start_day=02-02&end_day=03-01"
#key1 = '9d6779bced5b4349a063cb9c3db865bd'
#key2 = '817cf89869664a96880b17d3c8ecbe71'
#key3 = '2161818004a54e4a8aa40226af21c455'
BASE_WEATHER_URL = 'https://api.weatherbit.io/v2.0/history/daily?lat={}&lon={}&start_date={}&end_date={}&key=2161818004a54e4a8aa40226af21c455'
MAPBOX_GET_URL = 'https://api.mapbox.com/geocoding/v5/mapbox.places/-114.28125000002024%2C57.31093640737254.json?access_token=pk.eyJ1IjoiYXNoYXBpcm8yNzkiLCJhIjoiY2txM2NpZTA5MGFwejJvbncwZjg5eHloMiJ9.pOzgpqxmh3QSD0iew65rbg&cachebuster=1625549205587&autocomplete=false'

def index(request):
    return render(request, 'test_template.html', {})



def home(request):
    this_year = datetime.datetime.today().year
    YEARS = [this_year - i for i in range(21)]
    context = {'years_lst': YEARS, 'period': ['Daily', 'Weekly', 'Monthly', 'Year']}
    print(YEARS)
    if request.is_ajax():
        print('IT IS AJAX')
    if request.method == 'POST':
        print('its post')
        #lat lng
        request_body = request.POST.get('realData')
        select_year = request.POST.get('year')
        select_period = request.POST.get('period')
        if select_year == str(this_year):
            yesterday = (datetime.datetime.now() - datetime.timedelta(days=1)).date()
            end_day = yesterday.strftime('%Y-%m-%d')
            #start_day = (datetime.datetime.now() - datetime.timedelta(days=8)).date().strftime('%Y-%m-%d')
            start_day = f'{this_year}-01-01'
        else:
            start_day = f'{select_year}-01-01'
            end_day = f'{int(select_year)+1}-01-01'



        lat_lon_dict = (eval(request_body))
        print(lat_lon_dict)
        lat = lat_lon_dict['lat']
        lng = lat_lon_dict['lng']
        #datetime
        
        #weather request
        print(start_day, end_day)
        url = BASE_WEATHER_URL.format(lat, lng, start_day, end_day)
        print(url)
        #data = None
        #with urllib.request.urlopen(url) as response:
        #    data = json.load(response)

        #with open('sample_data.json') as f:
            #data = json.load(f)


        with open('year_weather.json') as f:
            data = json.load(f)


        city = data['city_name']
        context['static_var'] = city






        #average data
        iterate = 0
        weather_df = pd.DataFrame(data['data'])
        weather_df['datetime'] = pd.to_datetime(weather_df['datetime'])
        weather_df = weather_df.fillna(0)
        print(weather_df['datetime'])
        if select_period == 'Daily':
            context['daily'] = True
        elif select_period == 'Weekly':
            iterate = ceil(len(weather_df)/7)
            starter = 0
            seconder = 7
            pd_lst = []
            week_lst = []
            week_lst2 = []
            counter = 8
            for item in range(iterate):
                counter += 1
                week_lst.append(weather_df[starter:seconder]['datetime'].iloc[0])
                week_lst2.append(weather_df[starter:seconder]['datetime'].iloc[-1])
                weather_df.iloc[starter:seconder]['datetime'] = weather_df.iloc[starter:seconder]['datetime']
                pd_lst.append((weather_df.iloc[starter: seconder]))
                starter += 7
                seconder += 7

            for index, week in enumerate(week_lst):
                week = pd.Timestamp.to_pydatetime(week).strftime('%m-%d')
                week_end = pd.Timestamp.to_pydatetime(week_lst2[index]).strftime('%m-%d')
                week_lst[index] = pd.Series([f'{week}-{week_end}'], index=['datetime'])
                
            starter = 0
            seconder = 7
            for index, df in enumerate(pd_lst):
                x = df.mean().round(2)
                x = x.append(week_lst[index])
                #print(week_lst[index].iloc[0])
                pd_lst[index] = x
                #print(weather_df[starter:seconder]['datetime'])
                starter += 7
                seconder += 7

            context['pd_lst'] = pd_lst
        elif select_period == 'Monthly':
            month_len_lst = []
            for index, date in enumerate(weather_df['datetime'].dt.to_period('M')):
                if month_len_lst:
                    if date != weather_df['datetime'].dt.to_period('M')[index-1]:
                        month_len_lst.append(date.days_in_month)
                else:
                    month_len_lst.append(date.days_in_month)


            starter = 0
            seconder = month_len_lst[0]
            pd_lst_monthly = []
            month_lst = []
            for item in range(len(month_len_lst)):
                month_lst.append(weather_df.iloc[starter:seconder]['datetime'].iloc[0])
                weather_df.iloc[starter:seconder]['datetime'] = weather_df.iloc[starter:seconder]['datetime']
                pd_lst_monthly.append((weather_df[starter: seconder]))
                #rint(weather_df[starter: seconder])
                try:
                    starter += month_len_lst[item]
                    seconder += month_len_lst[item+1]
                except:
                    break

            for index, month in enumerate(month_lst):
                month_lst[index] = pd.Series([month], index=['datetime']).dt.strftime('%B')

            starter = 0
            seconder = 7
            for index, df in enumerate(pd_lst_monthly):
                x = df.mean().round(2)
                x = x.append(month_lst[index])
                #print(week_lst[index].iloc[0])
                pd_lst_monthly[index] = x
                #print(weather_df[starter:seconder]['datetime'])
                starter += 7
                seconder += 7


            context['pd_lst_monthly'] = pd_lst_monthly
        elif select_period == 'Year':
            year_mean = weather_df.mean().round(2)
            year_mean['datetime'] = select_year
            context['year_mean'] = year_mean
            context['year_mean_bool'] = True
        

        
        #chart = get_plot(weather_df, 'rh')
        #chart2 = get_plot(weather_df, 'min_temp')
        #chart3 = get_plot(weather_df, 'min_temp')
        #chart4 = get_plot(weather_df, 'min_temp')
        #chart5 = get_plot(weather_df, 'max_temp')
        
        #fig1, ax1 = plt.subplots()
        #fig2, ax2 = plt.subplots()
        #ax1.plot(weather_df['datetime'], weather_df['rh'], label='rh')
        #ax2.plot(weather_df['datetime'], weather_df['min_temp'], label='min_temp')



        #chart_lst = [get_plot(weather_df, cat) for cat in weather_df.columns]
        #context['chart'] = [fig1, fig2]
        #imgdata = StringIO()
        #img_graph = fig1.savefig(imgdata, format='svg')
        #imgdata.seek(0)
        #img_graph_data = imgdata.getvalue() 
        #context['test_chart'] = img_graph_data


        plotly_graph = get_plotly_graph(weather_df)
        context['plotly_graph'] = plotly_graph






        #form = Coords(lat=lat, lon=lng)
        #form.save()
        #print(Coords.objects.all())
        lat = round((lat), 5) 
        lng = round((lng), 5) 
        context['data'] = data
        context['coords'] = f'{lat}, {lng}'
        #print(pd_lst)
        print(request.POST.get('year'))
        print(request.POST.get('period'))
        context['chosen_period'] = select_period
        context['chosen_year'] = select_year
        context['labels'] = ['label', 'label2', 'label3', 'label4']
        return render(request, 'test_template.html', context)
    print(context)
    if request.method == 'GET':
        print('its get')
        context['labels'] = ['label', 'label2', 'label3', 'label4']
    return render(request, 'test_template.html', context)

maps/templates/default.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Accept coordinates as input to a geocoder</title>
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
<link href="https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js"></script>
<style>
body { margin: 0; padding: 0; }
#map { position: absolute; top: 0; bottom: 0; width: 100%; }
</style>

</head>
<body>
<div class="row">

<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.min.js"></script>
<link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.css" type="text/css">
<!-- Promise polyfill script required to use Mapbox GL Geocoder in IE 11 -->
<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>

<div id="map" style='width: 100%; height: 60%; top: 10%;'></div>

<script>
	mapboxgl.accessToken = 'pk.eyJ1IjoiYXNoYXBpcm8yNzkiLCJhIjoiY2txM2NpZTA5MGFwejJvbncwZjg5eHloMiJ9.pOzgpqxmh3QSD0iew65rbg';
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/ashapiro279/ckq62som3426o17pfga7v8t84',
        center: [-79.4512, 43.6568],
        zoom: 1
    });
    
    /* Given a query in the form "lng, lat" or "lat, lng"
     * returns the matching geographic coordinate(s)
     * as search results in carmen geojson format,
     * https://github.com/mapbox/carmen/blob/master/carmen-geojson.md */
    var coordinatesGeocoder = function (query) {
        // Match anything which looks like
        // decimal degrees coordinate pair.
        var matches = query.match(
            /^[ ]*(?:Lat: )?(-?\d+\.?\d*)[, ]+(?:Lng: )?(-?\d+\.?\d*)[ ]*$/i
        );
        if (!matches) {
            return null;
        }

        function coordinateFeature(lng, lat) {
            return {
                center: [lng, lat],
                geometry: {
                    type: 'Point',
                    coordinates: [lng, lat]
                },
                place_name: 'Lat: ' + lat + ' Lng: ' + lng,
                place_type: ['coordinate'],
                properties: {},
                type: 'Feature'
            };
        }

        var coord1 = Number(matches[1]);
        var coord2 = Number(matches[2]);
        var geocodes = [];

        if (coord1 < -90 || coord1 > 90) {
            // must be lng, lat
            geocodes.push(coordinateFeature(coord1, coord2));
        }

        if (coord2 < -90 || coord2 > 90) {
            // must be lat, lng
            geocodes.push(coordinateFeature(coord2, coord1));
        }

        if (geocodes.length === 0) {
            // else could be either lng, lat or lat, lng
            geocodes.push(coordinateFeature(coord1, coord2));
            geocodes.push(coordinateFeature(coord2, coord1));
        }

        return geocodes;
    };

    // Add the control to the map.
    map.addControl(
        new MapboxGeocoder({
            accessToken: mapboxgl.accessToken,
            localGeocoder: coordinatesGeocoder,
            zoom: 9,
            placeholder: '\tEnter a location',
            mapboxgl: mapboxgl
        })
    );
    map.addSource('my-data', {
  "type": "geojson",
  "data": {
    "type": "Feature",
    "geometry": {
      "type": "Point",
      "coordinates": [-77.0323, 38.9131]
    },
    "properties": {
      "title": "Mapbox DC",
      "marker-symbol": "monument"
    }
  }
});

</script>

</body>
</div>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<form action="/location/" method="post">
  {% csrf_token %}
  {{ form }}
  <label for="Location" style="bottom: 20;">Ex: 12, 70 </label>
  <input id="Location" type="text" style="bottom: 20;" name="Location" value="{{ current_name }}">
  <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
</button>
</form>

<h3>Your location is {{data}} and your url is {{url}}</h3>


</html>

maps/templates/searches.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    {% block style %}
    {% endblock style %}
</head>

<body>
    <div class="container-fluid">
        <form id="friend-form">
            <div class="row">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group col-4">
                    <label class="col-12">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% endfor %}
                <input type="submit" class="btn btn-primary" value="Create Friend" />
            </div>
        <form>
    </div>
    <hr />
    
    <div class="container-fluid">
        <table class="table table-striped table-sm" id="my_friends">
            <thead>
                <tr>
                    <th>Nick name</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Likes</th>
                    <th>DOB</th>
                    <th>lives in</th>
                </tr>
            </thead>
            <tbody>
            {% for friend in friends %}
            <tr>
                <td>{{friend.nick_name}}</td>
                <td>{{friend.first_name}}</td>
                <td>{{friend.last_name}}</td>
                <td>{{friend.likes}}</td>
                <td>{{friend.dob | date:"Y-m-d"}}</td>
                <td>{{friend.lives_in}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script>
        /*
            On submiting the form, send the POST ajax
            request to server and after successfull submission
            display the object.
        */
        $("#friend-form").submit(function (e) {
            // preventing from page reload and default actions
            e.preventDefault();
            // serialize the data for sending the form data.
            var serializedData = $(this).serialize();
            // make POST ajax call
            $.ajax({
                type: 'POST',
                url: "{% url 'post_friend' %}",
                data: serializedData,
                success: function (response) {
                    // on successfull creating object
                    // 1. clear the form.
                    $("#friend-form").trigger('reset');
                    // 2. focus to nickname input 
                    $("#id_nick_name").focus();
    
                    // display the newly friend to table.
                    var instance = JSON.parse(response["instance"]);
                    var fields = instance[0]["fields"];
                    $("#my_friends tbody").prepend(
                        `<tr>
                        <td>${fields["nick_name"]||""}</td>
                        <td>${fields["first_name"]||""}</td>
                        <td>${fields["last_name"]||""}</td>
                        <td>${fields["likes"]||""}</td>
                        <td>${fields["dob"]||""}</td>
                        <td>${fields["lives_in"]||""}</td>
                        </tr>`
                    )
                },
                error: function (response) {
                    // alert the error if any error occured
                    alert(response["responseJSON"]["error"]);
                }
            })
        })
        
    </script>
</body>

</html>